-- ============================================================
-- band_moods_admin_write_lockdown.sql
--
-- NOCH NICHT AUSGEFUEHRT. Nach fn_set_band_moods.sql auszufuehren
-- (siehe Completion Report fuer die genaue Reihenfolge) -- diese Datei
-- entzieht direkte Schreibrechte, die die vorherigen Klingt-nach-
-- Migrationen (Batch 1, Runde 1+2, Runde 3+4, STEINBACH-Korrektur)
-- benoetigten, jetzt aber nicht mehr, sobald der Admin-Schreibpfad
-- ausschliesslich ueber public.set_band_moods() laeuft.
--
-- Sprint: Admin "Klingt nach" -- Mood-Editor
-- Datum des Entwurfs: 20.07.2026
--
-- Vorbild/Muster: supabase/band_relations_admin_read_grant.sql
-- (identisches Prinzip: Sollzustand-Deklaration, REVOKE + GRANT SELECT
-- als expliziter, idempotenter Soll-Zustand statt Delta-Migration).
--
-- Bewusst NUR SELECT fuer service_role auf band_moods. Schreiben laeuft
-- ab sofort ausschliesslich ueber die SECURITY DEFINER Funktion
-- public.set_band_moods() (siehe supabase/fn_set_band_moods.sql).
--
-- Bisheriger Zustand (siehe supabase/setup-grants-and-seed.sql und
-- supabase/grant-service-role-permissions-v2.sql): service_role hatte
-- volles SELECT, INSERT, UPDATE, DELETE auf band_moods -- notwendig fuer
-- die bisherigen, einmaligen guard-gesicherten Import-/Korrektur-
-- Migrationen des Klingt-nach-Rollouts. Dieser Rollout ist
-- abgeschlossen (141/141 fachlich entschieden, PR #11 gemergt und
-- verifiziert) -- der laufende Admin-Betrieb braucht diese direkten
-- Schreibrechte nicht mehr.
--
-- Kein RLS-Bezug: service_role hat BYPASSRLS, Policies sind fuer diesen
-- Grant nicht entscheidungsrelevant (siehe supabase/enable-rls-app-tables.sql
-- fuer die anon-Policies, die von diesem Lockdown unberuehrt bleiben).
--
-- WICHTIG -- Reihenfolge: Diese Datei darf erst NACH erfolgreicher
-- Ausfuehrung von fn_set_band_moods.sql ausgefuehrt werden. In
-- umgekehrter Reihenfolge waere der Mood-Editor voruebergehend komplett
-- schreibunfaehig (weder direkte Grants noch RPC vorhanden).
--
-- Nachtrag 2A.1 (Live-Befund gegen Test UND Production): der urspruengliche
-- REVOKE unten (insert, update, delete) entsprach NICHT dem oben
-- beschriebenen Soll ("bewusst NUR SELECT") -- service_role besass live
-- weiterhin TRUNCATE, REFERENCES, TRIGGER und (nur ueber die rohe ACL
-- sichtbar, nicht ueber information_schema) MAINTAIN auf band_moods.
-- Herkunft verifiziert: kein projekteigener Grant (weder in diesem noch in
-- einem anderen supabase/*.sql-Skript wird band_moods TRUNCATE/REFERENCES/
-- TRIGGER/MAINTAIN gewaehrt), sondern eine bereits bestehende
-- schemaweite ALTER-DEFAULT-PRIVILEGES-Regel fuer Rolle postgres im Schema
-- public (pg_default_acl: public/postgres/r -> service_role erhaelt Dxtm,
-- auf Test zusaetzlich auch anon/authenticated). Diese Default-Privilege-
-- Regel gilt automatisch fuer JEDE von postgres neu angelegte Tabelle in
-- public -- betrifft also vermutlich weitere Tabellen, wurde aber bewusst
-- NICHT untersucht oder veraendert (kein Scope-Wechsel, keine schemaweite
-- Haertung in diesem Nachtrag). Der REVOKE unten wirkt ausschliesslich auf
-- die bereits bestehende band_moods-Tabelle und aendert die
-- Default-Privilege-Regel selbst nicht.
-- ============================================================

-- Sollzustand-Deklaration (idempotent):
-- Schreiben auf band_moods laeuft ausschliesslich ueber die SECURITY
-- DEFINER Funktionen public.set_band_moods() und
-- public.update_mood_band_assignments() (siehe supabase/fn_set_band_moods.sql,
-- supabase/fn_update_mood_band_assignments.sql). service_role bekommt hier
-- bewusst AUSSCHLIESSLICH SELECT auf die Tabelle -- kein INSERT/UPDATE/
-- DELETE und keine der aus der Default-Privilege-Regel geerbten
-- Struktur-Rechte (TRUNCATE/REFERENCES/TRIGGER/MAINTAIN).
revoke insert, update, delete, truncate, references, trigger, maintain
  on public.band_moods from service_role;

grant select on public.band_moods to service_role;
